# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:
  - /page/home
  - /page/error404
  - /page/private

## ignore by "slug" of contenttype
ignore_contenttype:
  - footers
