primary:
  - title: 'Get involved'
    path: /get-involved
    label: 'Get involved'
  - title: 'Provide your data'
    path: /share-your-data
    label: 'Share your data'
  - title: 'Use our data'
    path: /use-our-data
    label: 'Use our data'
footer:
  - title: Home
    path: homepage
    label: Home
  - title: 'About us'
    path: /about-us
    label: 'About us'
  - title: 'Terms & policies'
    link: http://europeana.eu/portal/rights/terms-and-policies.html
    label: 'Terms & policies'
  - title: Sitemap
    path: /sitemap
    label: Sitemap
Explorer-Europeana:
  - title: Search portal
    path: /sitemap
    label: Search portal
  - title: Labs
    path: /sitemap
    label: Labs
  - title: 1914-1918
    path: /sitemap
    label: 1914-1918
  - title: End user blog
    path: /sitemap
    label: End user blog
