# This file defines role-based access control for your Bolt site.
# Before making any modifications to this file, make sure you've thoroughly read
# the documentation at http://docs.bolt.cm/permissions, and understand the
# consequences of making uninformed changes to the roles and permissions.

# First, we need to define some roles. There are three built-in roles that you
# should never add manually:
# - 'root', the "superuser" role; Bolt will automatically grant all permissions
#   to this role. Manually adding it to any permission is pointless, because it
#   implicitly grants every permission anyway.
# - 'everyone', the "anonymous" role; every user automatically has this role.
#   Adding the 'everyone' role to any permission will grant it to all users.
# - 'owner': this role is only valid in the context of an individual content
#   item, and the user who "owns" the item (usually the person who created it)
#   will be in the 'owner' role.
# - 'anonymous': this role is automatically assigned at all times, even when
#   no user is logged in at all.
roles:
    editor:
        description: This user can edit some content.
        label: Editor
    chief-editor:
        description: This user can edit any content in the system.
        label: Chief Editor
    admin:
        description: User-level administrator.
        label: Administrator
    developer:
        description: Developer access. Only required to change system-level settings.
        label: Developer
    guest:
        description: This user can log on, but is not allowed to edit any content.
        label: Guest Editor
    blog-editor:
        description: This user can edit blogs in the system.
        label: Blog Editor

# Now we'll define some permissions. Each permission comes with a list of roles
# that grant access.

# The first set of permissions are the 'global' permissions; these are not tied
# to any content types, but rather apply to global, non-content activity in
# Bolt's backend. Most of these permissions map directly to backend routes;
# keep in mind, however, that routes do not always correspond to URL paths 1:1.
# The default set defined here is appropriate for most sites, so most likely,
# you will not have to change it.
# Also note that the 'editcontent' and 'overview' routes are special-cased
# inside the code, so they don't appear here.
global:
    about: [ editor, admin, developer, blog-editor ] # view the 'About Bolt' page
    activitylog: [ admin, developer ]
    clearcache: [ admin, developer ]
    contentaction: [ editor, admin, developer ]
    dashboard: [ everyone ]
    dbcheck: [ admin, developer ]
    dbupdate: [ admin, developer ]
    dbupdate_result: [ admin, developer ]
    extensions: [ developer ]
    fileedit: [ admin, developer ]
    files:config: [ developer ]
    files:theme: [ developer ]
    files:uploads: [ admin, developer, chief-editor, blog-editor ]
    files: [ editor, admin, developer, chief-editor, blog-editor ]
    prefill: [ developer ]
    settings: [ admin, developer, everyone ]
    translation: [ developer ]
    useraction: [ admin, developer ] # enable/disable/delete
    useredit: [ admin, developer ] # user settings
    users: [ admin, developer ] # view user overview
    maintenance-mode: [ everyone ] # view the frontend when in maintenance mode
    # The following permissions are particularly important: login and postLogin
    # determine who may see and use the login form. If you set them to anything
    # but 'anonymous', only users will be able to log in that are logged in
    # already, which is probably never what you want.
    login: [ anonymous ]
    postLogin: [ anonymous ]
    # Likewise, 'logout' needs to be granted to 'everyone', otherwise people
    # cannot log out anymore.
    logout: [ everyone ]

# For content type related actions, permissions can be set individually for
# each content type. For this, we define three groups of permission sets.
# The 'contenttype-all' permission sets *overrides*; any roles specified here
# will grant a permission for all content types, regardless of the rest of this
# section.
# The 'contenttype-default' contains rules that are used when the desired
# content type does not define a rule for this permission itself.
# The 'contenttypes' section specifies permissions for individual content
# types.
#
# To understand how this works, it may be best to follow the permission checker
# through its decision-making process.
#
# First, it checks whether the current user is in the "root" role; if so, it
# short-circuits and always grants anything unconditionally.
#
# Otherwise, it checks whether any of the current user's roles match any of the
# roles in contenttype-all/{permission}. If so, the search is over, and the
# permission can be granted.
#
# The next step is to find contenttypes/{contenttype}/{permission}. If it is
# found, then the permission can be granted if and only if any of the user's
# roles match any role in contenttypes/{contenttype}/{permission}.
#
# If either contenttypes/{contenttype} or
# contenttypes/{contenttype}/{permission} is absent, the permission checker
# uses contenttype-default/{permission} instead. If any role exists in both the
# user's roles and contenttype-default/{permission}, the permission can be
# granted.
#
# Note especially that an *empty* set of roles in the contenttype section means
# something else than the *absence* of the permission. If the permission is
# defined with an empty role list, it overrides the role list in
# contenttype-default; but if the permission is not mentioned, the
# corresponding entry in contenttype-default applies.
contenttype-all:
    edit: [ developer, admin ]
    create: [ developer, admin ]
    publish: [ developer, admin ]
    depublish: [ developer, admin ]
    change-ownership: [ developer, admin ]

contenttype-default:
    edit: [ editor, chief-editor ]
    create: [ editor, chief-editor ]
    change-ownership: [ owner ]
    view: [ editor, chief-editor ]
    publish: [ chief-editor ]
    depublish: [ chief-editor ]
    delete: [ developer, admin ]

contenttypes:
    structures:
        edit: [ developer, admin ]
        create: [ developer, admin ]
        change-ownership: [ developer, admin ]
        view: [ developer, admin ]
    homepage:
        edit: [ developer, admin ]
        create: [ developer, admin ]
        change-ownership: [ developer, admin ]
        view: [ developer, admin ]
    footers:
        edit: [ developer, admin ]
        create: [ developer, admin ]
        change-ownership: [ developer, admin ]
        view: [ developer, admin ]
    blogposts:
        edit: [ developer, admin, chief-editor, blog-editor ]
        create: [ developer, admin, chief-editor, blog-editor ]
        change-ownership: [ developer, admin, chief-editor, blog-editor ]
        view: [ developer, admin, chief-editor, blog-editor ]
